name: 'Deploy to OVH hosting'
description: 'Deploy a repositories contents to an OVH Hosting Plan with SSH support'
author: pitscher
branding:
  icon: 'truck'  
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'