name: 'Deploy to OVHcloud web hosting'

description: 'Deploy a repositories contents to an OVHcloud Hosting Plan with SSH support'

author: OVHcloud

branding:
  icon: 'truck'  
  color: 'blue'

on:
  push:
    branches: [ master ]
  
  workflow_dispatch:

jobs:
  deploy:    
    runs-on: ubuntu-20.04

    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq sshpass openssh-client
      - name: WakeUp website
        env:
            OVH_WEBSITE_URL: ${{ secrets.OVH_WEBSITE_URL }}
        run: curl --silent --insecure --location --write-out "%{http_code}" -o /dev/null ${OVH_WEBSITE_URL}

      - name: Clone over SSH
        env:
            OVH_SSH_HOST: ${{ secrets.OVH_SSH_HOST }}
            OVH_SSH_PORT: ${{ secrets.OVH_SSH_PORT }}
            OVH_SSH_USERNAME: ${{ secrets.OVH_SSH_USERNAME }}
            OVH_SSH_PASSWORD: ${{ secrets.OVH_SSH_PASSWORD }}
        run: sshpass -p ${OVH_SSH_PASSWORD} ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oLogLevel=quiet ${OVH_SSH_USERNAME}@${OVH_SSH_HOST} -p ${OVH_SSH_PORT} -- 'rm -rf ${HOME}/.powerworkflow && git clone '${GITHUB_SERVER_URL}'/'${GITHUB_REPOSITORY}'.git --single-branch --branch '${GITHUB_REF##*/}' ${HOME}/.powerworkflow'

      - name: Running install script over SSH
        env:
            OVH_SSH_HOST: ${{ secrets.OVH_SSH_HOST }}
            OVH_SSH_PORT: ${{ secrets.OVH_SSH_PORT }}
            OVH_SSH_USERNAME: ${{ secrets.OVH_SSH_USERNAME }}
            OVH_SSH_PASSWORD: ${{ secrets.OVH_SSH_PASSWORD }}
            OVH_WEBSITE_DOCUMENTROOT: ${{ secrets.OVH_WEBSITE_DOCUMENTROOT }}
            OVH_WEBSITE_ENTRYPOINT: ${{ secrets.OVH_WEBSITE_ENTRYPOINT }}
            OVH_WEBSITE_PUBLICDIR: ${{ secrets.OVH_WEBSITE_PUBLICDIR }}
            OVH_WEBSITE_URL: ${{ secrets.OVH_WEBSITE_URL }}
        run: sshpass -p ${OVH_SSH_PASSWORD} ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oLogLevel=quiet ${OVH_SSH_USERNAME}@${OVH_SSH_HOST} -p ${OVH_SSH_PORT} -- 'bash ${HOME}/.powerworkflow/install.sh -u '${OVH_WEBSITE_URL}' -d '${OVH_WEBSITE_DOCUMENTROOT}' -e '${OVH_WEBSITE_ENTRYPOINT}' -p '${OVH_WEBSITE_PUBLICDIR}''

      - name: WakeUp website
        env:
            OVH_WEBSITE_URL: ${{ secrets.OVH_WEBSITE_URL }}
        run: curl --silent --fail --insecure --location --write-out "%{http_code}" -o /dev/null ${OVH_WEBSITE_URL}